peliculas = [
    {"id": 1, "nombre": "Sueño de Fuga", "genero": "Drama", "precio": 8500.0, "activo": True,"imagen": "https://image.tmdb.org/t/p/w500/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg"},
    {"id": 2, "nombre": "El Padrino", "genero": "Crimen", "precio": 9800.0, "activo": True,"imagen": "https://image.tmdb.org/t/p/w500/ApiEfzSkrqS4m1L5a2GwWXzIiAs.jpg"},
    {"id": 3, "nombre": "Batman: El Caballero de la Noche", "genero": "Accion", "precio": 9200.0, "activo": True,"imagen": "https://image.tmdb.org/t/p/w500/8QDQExnfNFOtabLDKqfDQuHDsIg.jpg"},
    {"id": 4, "nombre": "Tiempos Violentos", "genero": "Crimen", "precio": 7900.0, "activo": True,"imagen": "https://image.tmdb.org/t/p/w500/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg"},
    {"id": 5, "nombre": "Forrest Gump", "genero": "Drama", "precio": 7400.0, "activo": True,"imagen": "https://image.tmdb.org/t/p/w500/azV6hV99lYkdhydsQbJCI6FqMl4.jpg"},
    {"id": 6, "nombre": "Alien - El octavo pasajero", "genero": "Ciencia Ficcion", "precio": 9500.0, "activo": True,"imagen": "https://image.tmdb.org/t/p/w500/pZ9cAe5FxexJjpCaeiETbXzz3Fs.jpg"},
    {"id": 7, "nombre": "El Club de la Pelea", "genero": "Drama", "precio": 7800.0, "activo": False,"imagen": "https://image.tmdb.org/t/p/w500/sgTAWJFaB2kBvdQxRGabYFiQqEK.jpg"},
    {"id": 8, "nombre": "Matrix", "genero": "Ciencia Ficcion", "precio": 8700.0, "activo": True,"imagen": "https://image.tmdb.org/t/p/w500/8rT9kG2EYkZpJmYCuTJNnPDEube.jpg"},
    {"id": 9, "nombre": "Buenos Muchachos", "genero": "Crimen", "precio": 7600.0, "activo": True,"imagen": "https://image.tmdb.org/t/p/w500/3Yy0zBO9AlyAZH1cTI8Ko2ouCi.jpg"},
    {"id": 10, "nombre": "Interestelar", "genero": "Ciencia Ficcion", "precio": 9900.0, "activo": True,"imagen": "https://image.tmdb.org/t/p/w500/9cTfZWP5TfdnmAjiD6ZBXWIJ7O9.jpg"},
    {"id": 11, "nombre": "Gladiador", "genero": "Accion", "precio": 8200.0, "activo": True,"imagen": "https://image.tmdb.org/t/p/w500/90QFOG5zSN4cbrIVs4DL4ePAuA5.jpg"},
    {"id": 12, "nombre": "Titanic", "genero": "Romance", "precio": 7300.0, "activo": False,"imagen": "https://image.tmdb.org/t/p/w500/g7gdURTtFOmMdnPSVJtQBXtxTBk.jpg"},
    {"id": 13, "nombre": "El Silencio de los Inocentes", "genero": "Suspenso", "precio": 8600.0, "activo": True,"imagen": "https://image.tmdb.org/t/p/w500/8FdQQ3cUCs9goEOr1qUFaHackoJ.jpg"},
    {"id": 14, "nombre": "Rescatando al Soldado Ryan", "genero": "Belica", "precio": 9100.0, "activo": True,"imagen": "https://image.tmdb.org/t/p/w500/dcKfD8xWf8XnS3tHVp7v331wdNT.jpg"},
    {"id": 15, "nombre": "Milagros Inesperados", "genero": "Drama", "precio": 8100.0, "activo": True,"imagen": "https://image.tmdb.org/t/p/w500/aBQiJRxGRrX0mXFMjxyzWYFtEnf.jpg"},
    {"id": 16, "nombre": "Pecados Capitales", "genero": "Suspenso", "precio": 8500.0, "activo": True,"imagen": "https://image.tmdb.org/t/p/w500/uVPcVz4b2hnSGrXYLdIGRXwcivs.jpg"},
    {"id": 17, "nombre": "Whiplash: Música y Obsesión", "genero": "Drama", "precio": 7200.0, "activo": True,"imagen": "https://image.tmdb.org/t/p/w500/uy36CPy5ARuC8qrH8Esg2ndFyJ5.jpg"},
    {"id": 18, "nombre": "El Gran Truco", "genero": "Misterio", "precio": 7900.0, "activo": True,"imagen": "https://image.tmdb.org/t/p/w500/lIl2CrnWohGrZSO9eyKRptxZ7Hs.jpg"},
    {"id": 19, "nombre": "Guasón", "genero": "Drama", "precio": 9300.0, "activo": False,"imagen": "https://image.tmdb.org/t/p/w500/g9l7iLYusH82bbEbwGCJzhVkOe2.jpg"},
    {"id": 20, "nombre": "Parásitos", "genero": "Drama", "precio": 8800.0, "activo": True,"imagen": "https://image.tmdb.org/t/p/w500/4N55tgxDW0RRATyrZHbx0q9HUKv.jpg"},
    {"id": 21, "nombre": "Avengers: Endgame", "genero": "Accion", "precio": 10500.0, "activo": True,"imagen": "https://image.tmdb.org/t/p/w500/br6krBFpaYmCSglLBWRuhui7tPc.jpg"},
    {"id": 22, "nombre": "Iron Man", "genero": "Accion", "precio": 8200.0, "activo": True,"imagen": "https://image.tmdb.org/t/p/w500/tFCTNx7foAsUQpgu2x1KjAJD1wT.jpg"},
    {"id": 23, "nombre": "Pantera Negra", "genero": "Accion", "precio": 8400.0, "activo": True,"imagen": "https://image.tmdb.org/t/p/w500/lAPzezdc5E6DFnttJwCWXZ9A9C6.jpg"},
    {"id": 24, "nombre": "Doctor Strange", "genero": "Fantasia", "precio": 8600.0, "activo": True,"imagen": "https://image.tmdb.org/t/p/w500/wJEZI3PWyMW7qcW6n9jyCh7Cclf.jpg"},
    {"id": 25, "nombre": "Guardianes de la Galaxia", "genero": "Ciencia Ficcion", "precio": 8900.0, "activo": True,"imagen": "https://image.tmdb.org/t/p/w500/zqZNnuMtrmK99Xux91KiCdnZxgb.jpg"},
    {"id": 26, "nombre": "Deadpool", "genero": "Comedia", "precio": 8700.0, "activo": False,"imagen": "https://image.tmdb.org/t/p/w500/3TUYy0XvhPQBhrXJwRIaOoYFOBO.jpg"},
    {"id": 27, "nombre": "Shrek", "genero": "Animacion", "precio": 4500.0, "activo": True,"imagen": "https://image.tmdb.org/t/p/w500/jTQONM7jt1yv2lL972TtmWO0UIZ.jpg"},
    {"id": 28, "nombre": "Toy Story", "genero": "Animacion", "precio": 5000.0, "activo": True,"imagen": "https://image.tmdb.org/t/p/w500/3Rfvhy1Nl6sSGJwyjb0QiZzZYlB.jpg"},
    {"id": 29, "nombre": "Buscando a Nemo", "genero": "Animacion", "precio": 4800.0, "activo": True,"imagen": "https://image.tmdb.org/t/p/w500/lwH5KqAynqqnpIQK9g6B80ksAtU.jpg"},
    {"id": 30, "nombre": "Intensa-Mente", "genero": "Animacion", "precio": 6200.0, "activo": True,"imagen": "https://image.tmdb.org/t/p/w500/sG3bHZWCMOZwhUq71WbPG9Vrrwc.jpg"},
    {"id": 31, "nombre": "El Conjuro", "genero": "Terror", "precio": 7600.0, "activo": True,"imagen": "https://image.tmdb.org/t/p/w500/sKuHxkCogdk6YWzTyXYPoo9qd9n.jpg"},
    {"id": 32, "nombre": "Eso", "genero": "Terror", "precio": 7300.0, "activo": True,"imagen": "https://image.tmdb.org/t/p/w500/sSrj4lnhrb113DOPEPTaO2jaDk3.jpg"},
    {"id": 33, "nombre": "Un Lugar en Silencio", "genero": "Terror", "precio": 8100.0, "activo": True,"imagen": "https://image.tmdb.org/t/p/w500/5pairI20KJs1SEa4Z8yAsPR779m.jpg"},
    {"id": 34, "nombre": "El Legado del Diablo", "genero": "Terror", "precio": 8400.0, "activo": False,"imagen": "https://image.tmdb.org/t/p/w500/ApiEfzSkrqS4m1L5a2GwWXzIiAs.jpg"},
    {"id": 35, "nombre": "¡Huye!", "genero": "Terror", "precio": 7900.0, "activo": True,"imagen": "https://image.tmdb.org/t/p/w500/xiMoqa0bmjuyuXYqKGwrTSJL8nI.jpg"},
    {"id": 36, "nombre": "La La Land", "genero": "Musical", "precio": 6800.0, "activo": True,"imagen": "https://image.tmdb.org/t/p/w500/7pFsAaJmiOppVHcldBzg8JKBHwe.jpg"},
    {"id": 37, "nombre": "Diario de una Pasión", "genero": "Romance", "precio": 6500.0, "activo": True,"imagen": "https://image.tmdb.org/t/p/w500/gFCnDKfsZWzyv9sweizVC4EWn06.jpg"},
    {"id": 38, "nombre": "John Wick", "genero": "Accion", "precio": 9100.0, "activo": True,"imagen": "https://image.tmdb.org/t/p/w500/tDl5ac1VJwMRvlgINDCsDCqg9CE.jpg"},
    {"id": 39, "nombre": "Mad Max: Furia en el Camino", "genero": "Accion", "precio": 9300.0, "activo": True,"imagen": "https://image.tmdb.org/t/p/w500/fnY0VRsb31A5RLVCBjuR6EFUlo2.jpg"},
    {"id": 40, "nombre": "Blade Runner 2049", "genero": "Ciencia Ficcion", "precio": 9900.0, "activo": True,"imagen": "https://image.tmdb.org/t/p/w500/cOt8SQwrxpoTv9Bc3kyce3etkZX.jpg"},
    {"id": 41, "nombre": "Volver al Futuro", "genero": "Ciencia Ficcion", "precio": 7000.0, "activo": True,"imagen": "https://image.tmdb.org/t/p/w500/owk40tn1sFJmC7bhamEpmhdZPKa.jpg"},
    {"id": 42, "nombre": "Jurassic Park", "genero": "Aventura", "precio": 7800.0, "activo": True,"imagen": "https://image.tmdb.org/t/p/w500/h831eszSFmEyr94WKcgscqPIRbh.jpg"},
    {"id": 43, "nombre": "El Rey León", "genero": "Animacion", "precio": 5200.0, "activo": True,"imagen": "https://image.tmdb.org/t/p/w500/b0MxU37dNmMwKtoPVYPKOZSIrIn.jpg"},
    {"id": 44, "nombre": "Monsters Inc.", "genero": "Animacion", "precio": 4900.0, "activo": True,"imagen": "https://image.tmdb.org/t/p/w500/g3SgHEb5ej2MioGfYLrZVshF909.jpg"},
    {"id": 45, "nombre": "Coco", "genero": "Animacion", "precio": 6100.0, "activo": True,"imagen": "https://image.tmdb.org/t/p/w500/vwsFGblLYxWBNjg9pdWN1Mm5YfW.jpg"},
    {"id": 46, "nombre": "Avatar", "genero": "Ciencia Ficcion", "precio": 10400.0, "activo": True,"imagen": "https://image.tmdb.org/t/p/w500/t5T3LPbLLgP2OP6kloM9p2PXpJL.jpg"},
    {"id": 47, "nombre": "Top Gun: Maverick", "genero": "Accion", "precio": 9700.0, "activo": True,"imagen": "https://image.tmdb.org/t/p/w500/AlWpEpQq0RgZIXVHAHZtFhEvRgd.jpg"},
    {"id": 48, "nombre": "Misión Imposible", "genero": "Accion", "precio": 8900.0, "activo": True,"imagen": "https://image.tmdb.org/t/p/w500/xCpmxw3UUjv4PGzbIPOHeoKAV0l.jpg"},
    {"id": 49, "nombre": "Los Juegos del Hambre", "genero": "Aventura", "precio": 7600.0, "activo": False,"imagen": "https://image.tmdb.org/t/p/w500/qSEn7KsGchT7qB08HlviyeTPrEr.jpg"},
    {"id": 50, "nombre": "Spider-Man: Sin Camino a Casa", "genero": "Accion", "precio": 10800.0, "activo": True,"imagen": "https://image.tmdb.org/t/p/w500/miZFgV81xG324rpUknQX8dtXuBl.jpg"}]