peliculas = [
    {"id": 1, "nombre": "Sueño de Fuga", "genero": "Drama", "precio": 8500.0, "activo": True},
    {"id": 2, "nombre": "El Padrino", "genero": "Crimen", "precio": 9800.0, "activo": True},
    {"id": 3, "nombre": "Batman: El Caballero de la Noche", "genero": "Accion", "precio": 9200.0, "activo": True},
    {"id": 4, "nombre": "Tiempos Violentos", "genero": "Crimen", "precio": 7900.0, "activo": True},
    {"id": 5, "nombre": "Forrest Gump", "genero": "Drama", "precio": 7400.0, "activo": True},
    {"id": 6, "nombre": "El Origen", "genero": "Ciencia Ficcion", "precio": 9500.0, "activo": True},
    {"id": 7, "nombre": "El Club de la Pelea", "genero": "Drama", "precio": 7800.0, "activo": False},
    {"id": 8, "nombre": "Matrix", "genero": "Ciencia Ficcion", "precio": 8700.0, "activo": True},
    {"id": 9, "nombre": "Buenos Muchachos", "genero": "Crimen", "precio": 7600.0, "activo": True},
    {"id": 10, "nombre": "Interestelar", "genero": "Ciencia Ficcion", "precio": 9900.0, "activo": True},
    {"id": 11, "nombre": "Gladiador", "genero": "Accion", "precio": 8200.0, "activo": True},
    {"id": 12, "nombre": "Titanic", "genero": "Romance", "precio": 7300.0, "activo": False},
    {"id": 13, "nombre": "El Silencio de los Inocentes", "genero": "Suspenso", "precio": 8600.0, "activo": True},
    {"id": 14, "nombre": "Rescatando al Soldado Ryan", "genero": "Belica", "precio": 9100.0, "activo": True},
    {"id": 15, "nombre": "Milagros Inesperados", "genero": "Drama", "precio": 8100.0, "activo": True},
    {"id": 16, "nombre": "Pecados Capitales", "genero": "Suspenso", "precio": 8500.0, "activo": True},
    {"id": 17, "nombre": "Whiplash: Música y Obsesión", "genero": "Drama", "precio": 7200.0, "activo": True},
    {"id": 18, "nombre": "El Gran Truco", "genero": "Misterio", "precio": 7900.0, "activo": True},
    {"id": 19, "nombre": "Guasón", "genero": "Drama", "precio": 9300.0, "activo": False},
    {"id": 20, "nombre": "Parásitos", "genero": "Drama", "precio": 8800.0, "activo": True},
    {"id": 21, "nombre": "Avengers: Endgame", "genero": "Accion", "precio": 10500.0, "activo": True},
    {"id": 22, "nombre": "Iron Man", "genero": "Accion", "precio": 8200.0, "activo": True},
    {"id": 23, "nombre": "Pantera Negra", "genero": "Accion", "precio": 8400.0, "activo": True},
    {"id": 24, "nombre": "Doctor Strange", "genero": "Fantasia", "precio": 8600.0, "activo": True},
    {"id": 25, "nombre": "Guardianes de la Galaxia", "genero": "Ciencia Ficcion", "precio": 8900.0, "activo": True},
    {"id": 26, "nombre": "Deadpool", "genero": "Comedia", "precio": 8700.0, "activo": False},
    {"id": 27, "nombre": "Shrek", "genero": "Animacion", "precio": 4500.0, "activo": True},
    {"id": 28, "nombre": "Toy Story", "genero": "Animacion", "precio": 5000.0, "activo": True},
    {"id": 29, "nombre": "Buscando a Nemo", "genero": "Animacion", "precio": 4800.0, "activo": True},
    {"id": 30, "nombre": "Intensa-Mente", "genero": "Animacion", "precio": 6200.0, "activo": True},
    {"id": 31, "nombre": "El Conjuro", "genero": "Terror", "precio": 7600.0, "activo": True},
    {"id": 32, "nombre": "Eso", "genero": "Terror", "precio": 7300.0, "activo": True},
    {"id": 33, "nombre": "Un Lugar en Silencio", "genero": "Terror", "precio": 8100.0, "activo": True},
    {"id": 34, "nombre": "El Legado del Diablo", "genero": "Terror", "precio": 8400.0, "activo": False},
    {"id": 35, "nombre": "¡Huye!", "genero": "Terror", "precio": 7900.0, "activo": True},
    {"id": 36, "nombre": "La La Land", "genero": "Musical", "precio": 6800.0, "activo": True},
    {"id": 37, "nombre": "Diario de una Pasión", "genero": "Romance", "precio": 6500.0, "activo": True},
    {"id": 38, "nombre": "John Wick", "genero": "Accion", "precio": 9100.0, "activo": True},
    {"id": 39, "nombre": "Mad Max: Furia en el Camino", "genero": "Accion", "precio": 9300.0, "activo": True},
    {"id": 40, "nombre": "Blade Runner 2049", "genero": "Ciencia Ficcion", "precio": 9900.0, "activo": True},
    {"id": 41, "nombre": "Volver al Futuro", "genero": "Ciencia Ficcion", "precio": 7000.0, "activo": True},
    {"id": 42, "nombre": "Jurassic Park", "genero": "Aventura", "precio": 7800.0, "activo": True},
    {"id": 43, "nombre": "El Rey León", "genero": "Animacion", "precio": 5200.0, "activo": True},
    {"id": 44, "nombre": "Monsters Inc.", "genero": "Animacion", "precio": 4900.0, "activo": True},
    {"id": 45, "nombre": "Coco", "genero": "Animacion", "precio": 6100.0, "activo": True},
    {"id": 46, "nombre": "Avatar", "genero": "Ciencia Ficcion", "precio": 10400.0, "activo": True},
    {"id": 47, "nombre": "Top Gun: Maverick", "genero": "Accion", "precio": 9700.0, "activo": True},
    {"id": 48, "nombre": "Misión Imposible", "genero": "Accion", "precio": 8900.0, "activo": True},
    {"id": 49, "nombre": "Los Juegos del Hambre", "genero": "Aventura", "precio": 7600.0, "activo": False},
    {"id": 50, "nombre": "Spider-Man: Sin Camino a Casa", "genero": "Accion", "precio": 10800.0, "activo": True}]